apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: phrasal-frontend

build:
  artifacts:
    - image: phrasal-frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true

manifests:
  rawYaml:
    - ../k8s/base/frontend-configmap.yaml
    - ../k8s/base/frontend-deployment.yaml
    - ../k8s/base/frontend-service.yaml

deploy:
  kubeContext: minikube
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: phrasal-frontend
    port: 3000
    localPort: 3000
