apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: backend

build:
  artifacts:
    - image: backend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
    useBuildkit: true

manifests:
  rawYaml:
    - ../k8s/base/backend-configmap.yaml
    - ../k8s/base/backend-secret.yaml
    - ../k8s/base/postgres-statefulset.yaml
    - ../k8s/base/postgres-service.yaml
    - ../k8s/base/backend-deployment.yaml
    - ../k8s/base/backend-service.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: backend
    port: 8080
    localPort: 8080
