INSERT INTO phrasal_verbs (verb, definition, sentences, words_to_hide, is_learned) VALUES
  ('Act out', 'To perform a role or behavior', '["The students acted out a scene from the play."]'::jsonb, '["acted out"]'::jsonb, false),
  ('Act up', 'To behave inappropriately or malfunction', '["The computer started to act up and froze."]'::jsonb, '["act up"]'::jsonb, false),
  ('Ask for', 'To request or invite someone to do something', '["I''m going to ask for help with this difficult task."]'::jsonb, '["ask for"]'::jsonb, false),
  ('Back up', 'To support or assist someone or something', '["Can you back up your claims with evidence?"]'::jsonb, '["back up"]'::jsonb, false),
  ('Back up', 'To reverse or move backward', '["Could you back up the car so I can park?"]'::jsonb, '["back up"]'::jsonb, false),
  ('Be cut out for', 'To be suited for a particular role or occupation', '["She is definitely cut out for a career in medicine."]'::jsonb, '["cut out for"]'::jsonb, false),
  ('Blow up', 'To explode or burst into pieces', '["The fireworks will blow up in the sky tonight."]'::jsonb, '["blow up"]'::jsonb, false),
  ('Blow up', 'To lose one''s temper or become angry', '["He blew up at his colleague during the meeting."]'::jsonb, '["blew up"]'::jsonb, false),
  ('Break away', 'To flee or escape from someone or something physically', '["The puppy slipped its leash and tried to break away into the woods."]'::jsonb, '["break away"]'::jsonb, false),
  ('Break away', 'To separate from a larger group or organization', '["The cyclist decided to break away from the main pack and pedal ahead."]'::jsonb, '["break away"]'::jsonb, false),
  ('Break down', 'To stop working due to a mechanical or technical failure', '["My ten-year-old car finally broke down on the highway this morning."]'::jsonb, '["broke down"]'::jsonb, false),
  ('Break down', 'To lose emotional control and start crying', '["When she heard the devastating news, she simply broke down and wept."]'::jsonb, '["broke down"]'::jsonb, false),
  ('Break down', 'To divide complex information into smaller, simpler parts', '["Can you break down the quarterly expenses so we can easily see where our money went?"]'::jsonb, '["break down"]'::jsonb, false),
  ('Break in', 'To enter a building or place forcibly or illegally', '["The thief attempted to break in to the house."]'::jsonb, '["break in"]'::jsonb, false),
  ('Break off', 'To suddenly stop speaking in the middle of a sentence', '["She broke off mid-sentence when the loud thunder rattled the windows."]'::jsonb, '["broke off"]'::jsonb, false),
  ('Break off', 'To end a relationship or conversation abruptly', '["After realizing they were fundamentally incompatible, they decided to break off their engagement."]'::jsonb, '["break off"]'::jsonb, false),
  ('Break off', 'To detach or separate a piece from a larger object', '["He broke off a small piece of the chocolate bar and handed it to me."]'::jsonb, '["broke off"]'::jsonb, false),
  ('Break out', 'To escape from confinement or captivity', '["The notorious thief managed to break out of the high-security prison last night."]'::jsonb, '["break out"]'::jsonb, false),
  ('Break out', 'To start suddenly and spread rapidly', '["Panic broke out in the stadium when the fire alarm suddenly sounded."]'::jsonb, '["broke out"]'::jsonb, false),
  ('Break out', 'To develop a skin rash, acne, or other skin irritation', '["She tends to break out in hives whenever she eats strawberries."]'::jsonb, '["break out"]'::jsonb, false),
  ('Break through', 'To overcome an obstacle or make a significant achievement', '["They managed to break through the language barrier."]'::jsonb, '["break through"]'::jsonb, false),
  ('Bring along', 'To bring someone or something with you', '["Don''t forget to bring along your passport."]'::jsonb, '["bring along"]'::jsonb, false),
  ('Bring in', 'To introduce or earn a certain amount of money', '["The new marketing campaign really helped bring in more customers."]'::jsonb, '["bring in"]'::jsonb, false),
  ('Bring in', 'To move something from outside into an indoor space', '["It''s starting to rain; we need to bring in the patio furniture."]'::jsonb, '["bring in"]'::jsonb, false),
  ('Bring out', 'To carry something from inside to outside', '["Let''s bring out the cake and sing happy birthday."]'::jsonb, '["bring out"]'::jsonb, false),
  ('Bring out', 'To release or publish something to the public', '["The author plans to bring out a new novel next year."]'::jsonb, '["bring out"]'::jsonb, false),
  ('Bring out', 'To make a quality or feature more noticeable or vivid', '["That blue shirt really brings out the color of your eyes."]'::jsonb, '["brings out"]'::jsonb, false),
  ('Brush off', 'To dismiss or ignore someone or something casually', '["He brushed off my suggestion and continued with his plan."]'::jsonb, '["brushed off"]'::jsonb, false),
  ('Build on', 'To develop or expand on something already existing', '["We need to build on the success of our previous project."]'::jsonb, '["build on"]'::jsonb, false),
  ('Call for', 'To require or demand something', '["This situation calls for immediate action."]'::jsonb, '["calls for"]'::jsonb, false),
  ('Call in', 'To request someone''s presence or services', '["The expert was called in to investigate the crime scene."]'::jsonb, '["called in"]'::jsonb, false),
  ('Call out', 'To shout or say something loudly and clearly', '["The teacher called out the answer to the question."]'::jsonb, '["called out"]'::jsonb, false),
  ('Call up', 'To make a telephone call', '["I''ll call up the restaurant and make a reservation."]'::jsonb, '["call up"]'::jsonb, false),
  ('Carried away', 'To become overly excited or emotional in a situation', '["She got carried away and spent all her savings on the shopping spree."]'::jsonb, '["carried away"]'::jsonb, false),
  ('Carry on', 'To continue with an activity or life in general, often through difficulty', '["Sorry to interrupt, please carry on with your meeting."]'::jsonb, '["carry on"]'::jsonb, false),
  ('Carry out', 'To complete or perform a task or action', '["We need to carry out a thorough investigation."]'::jsonb, '["carry out"]'::jsonb, false),
  ('Catch on', 'To understand or grasp something, often after a delay', '["He didn''t get the joke at first, but he finally caught on."]'::jsonb, '["caught on"]'::jsonb, false),
  ('Catch on', 'To become widely popular or accepted by many people', '["Electric vehicles are really catching on these days."]'::jsonb, '["catching on"]'::jsonb, false),
  ('Catch up', 'To reach the same level or position as someone who is ahead of you', '["Walk faster so you can catch up with the group."]'::jsonb, '["catch up"]'::jsonb, false),
  ('Catch up', 'To spend time with someone to hear about what is new in their life', '["Let''s get coffee and catch up!"]'::jsonb, '["catch up"]'::jsonb, false),
  ('Catch up', 'To complete tasks or work that you have fallen behind on', '["I need to catch up on my emails."]'::jsonb, '["catch up"]'::jsonb, false),
  ('Catch up', 'To become deeply absorbed or involved in a situation', '["She got so caught up in the drama that she lost track of time."]'::jsonb, '["caught up"]'::jsonb, false),
  ('Check off', 'To mark or indicate that something has been completed or verified', '["I''ll check off the items on the list as we go."]'::jsonb, '["check off"]'::jsonb, false),
  ('Check over', 'To review or examine something carefully', '["Please check over the document for any errors."]'::jsonb, '["check over"]'::jsonb, false),
  ('Check up on', 'To verify or investigate the condition or progress of something', '["The doctor wants to check up on your recovery."]'::jsonb, '["check up on"]'::jsonb, false),
  ('Clean out', 'To empty or remove the contents of something', '["I need to clean out the garage and get rid of old items."]'::jsonb, '["clean out"]'::jsonb, false),
  ('Clean up', 'To tidy or make something clean and neat', '["They need to clean up the room before the guests arrive."]'::jsonb, '["clean up"]'::jsonb, false),
  ('Come about', 'To happen or occur', '["I''m not sure how it came about but I''m glad it did."]'::jsonb, '["came about"]'::jsonb, false),
  ('Come along', 'To make progress or improve', '["How is your project coming along?"]'::jsonb, '["coming along"]'::jsonb, false),
  ('Come along', 'To accompany or join someone', '["Will you come along to the party with me?"]'::jsonb, '["come along"]'::jsonb, false),
  ('Come away', 'To leave a place or experience while retaining a new feeling, impression, or object', '["I came away from the seminar feeling inspired."]'::jsonb, '["came away"]'::jsonb, false),
  ('Come away', 'To become detached while still remaining in your hand', '["The door handle came away in my hand."]'::jsonb, '["came away"]'::jsonb, false),
  ('Come back', 'To return to a place or situation', '["He promised to come back and visit us next year."]'::jsonb, '["come back"]'::jsonb, false),
  ('Come by', 'To obtain or acquire something', '["I managed to come by some concert tickets for tonight."]'::jsonb, '["come by"]'::jsonb, false),
  ('Come down', 'To move from a higher to a lower position', '["The elevator malfunctioned so we had to come down the stairs."]'::jsonb, '["come down"]'::jsonb, false),
  ('Come down on', 'To criticize or reprimand someone heavily', '["The boss came down on him for consistently being late to work."]'::jsonb, '["came down on"]'::jsonb, false),
  ('Come down with', 'To become ill with a particular illness or condition', '["She came down with the flu and had to stay home from work."]'::jsonb, '["came down with"]'::jsonb, false),
  ('Come forward', 'To offer oneself for a task position or help', '["If anyone has any information please come forward and speak to the authorities."]'::jsonb, '["come forward"]'::jsonb, false),
  ('Come in', 'To enter a place', '["Please knock before you come in."]'::jsonb, '["come in"]'::jsonb, false),
  ('Come off', 'To succeed or produce the intended result', '["The whole business deal just didn''t come off."]'::jsonb, '["come off"]'::jsonb, false),
  ('Come off', 'To detach or be removed from a surface', '["The button came off my coat."]'::jsonb, '["came off"]'::jsonb, false),
  ('Come off', 'To be removed from a hard surface (stains, marks)', '["That grease stain just won''t come off the kitchen counter."]'::jsonb, '["come off"]'::jsonb, false),
  ('Come off', 'To give a particular impression or come across in a certain way', '["He tried to be helpful, but he came off as bossy."]'::jsonb, '["came off"]'::jsonb, false),
  ('Come on', 'To encourage or urge someone', '["Come on you can do it!"]'::jsonb, '["Come on"]'::jsonb, false),
  ('Come out', 'To be revealed or made public', '["The truth finally came out in court."]'::jsonb, '["came out"]'::jsonb, false),
  ('Come out', 'To be removed from fabric through washing', '["This coffee stain will easily come out in the wash."]'::jsonb, '["come out"]'::jsonb, false),
  ('Come out', 'To emerge from an enclosed space or leave a building', '["She just came out of the building."]'::jsonb, '["came out"]'::jsonb, false),
  ('Come out', 'To be published, released, or made available to the public', '["The new movie comes out next week."]'::jsonb, '["comes out"]'::jsonb, false),
  ('Come over', 'To visit someone''s place', '["Why don''t you come over to my house this weekend?"]'::jsonb, '["come over"]'::jsonb, false),
  ('Come up', 'To arise or occur unexpectedly', '["An unexpected problem came up at work, so I have to stay late."]'::jsonb, '["came up"]'::jsonb, false),
  ('Come up', 'To rise or approach (sun, tide, or deadline)', '["The sun came up early this morning."]'::jsonb, '["came up"]'::jsonb, false),
  ('Come up with', 'To actively generate, invent, or find something that is needed', '["We need to brainstorm and come up with a solution."]'::jsonb, '["come up with"]'::jsonb, false),
  ('Count on', 'To rely on or trust someone or something', '["You can always count on me for support."]'::jsonb, '["count on"]'::jsonb, false),
  ('Cut down on', 'To reduce the amount or quantity of something', '["I''m trying to cut down on caffeine."]'::jsonb, '["cut down on"]'::jsonb, false),
  ('Deal with', 'To handle or manage a situation or problem', '["We need to deal with this issue immediately."]'::jsonb, '["deal with"]'::jsonb, false),
  ('Do away with', 'To eliminate or get rid of something', '["Let''s do away with unnecessary paperwork."]'::jsonb, '["do away with"]'::jsonb, false),
  ('Do up', 'To fasten or decorate something', '["She did up her hair and put on a beautiful dress for the party."]'::jsonb, '["did up"]'::jsonb, false),
  ('Dress up', 'To wear formal or fancy clothing for a special occasion', '["We should dress up for the wedding."]'::jsonb, '["dress up"]'::jsonb, false),
  ('Eat up', 'To consume all the food', '["He ate up his entire meal in just a few minutes."]'::jsonb, '["ate up"]'::jsonb, false),
  ('Fall back on', 'To rely on something as a last resort or backup', '["If I can''t find a job I might fall back on my savings."]'::jsonb, '["fall back on"]'::jsonb, false),
  ('Fall in', 'To collapse inward or form a line or formation', '["The old building finally fell in after years of neglect."]'::jsonb, '["fell in"]'::jsonb, false),
  ('Fall out', 'To have a disagreement or argument', '["They fell out over a trivial issue and stopped speaking to each other."]'::jsonb, '["fell out"]'::jsonb, false),
  ('Fall out', 'To unintentionally drop an object', '["Her credit card fell out of her pocket."]'::jsonb, '["fell out"]'::jsonb, false),
  ('Fall through', 'To fail to happen or be completed as planned', '["Our plans to go on a trip fell through due to bad weather."]'::jsonb, '["fell through"]'::jsonb, false),
  ('Figure out', 'To understand or solve something', '["She finally figured out the solution to the puzzle."]'::jsonb, '["figured out"]'::jsonb, false),
  ('Find out', 'To discover or obtain information', '["I need to find out what time the meeting starts."]'::jsonb, '["find out"]'::jsonb, false),
  ('Get along with', 'To have a harmonious, conflict-free relationship with someone', '["I get along with my new coworkers really well."]'::jsonb, '["get along with"]'::jsonb, false),
  ('Get along with', 'To manage or cope with a situation', '["How are you getting along with your studies?"]'::jsonb, '["getting along with"]'::jsonb, false),
  ('Get away', 'To go on a vacation or take a break from your routine', '["I really need to get away for the weekend and relax."]'::jsonb, '["get away"]'::jsonb, false),
  ('Get away', 'To escape from a person or dangerous situation', '["The suspect managed to get away from the police."]'::jsonb, '["get away"]'::jsonb, false),
  ('Get by', 'To manage or survive with the available resources or income', '["They can get by with their current budget."]'::jsonb, '["get by"]'::jsonb, false),
  ('Get in', 'To enter or arrive at a place', '["He needs to get in before the meeting starts."]'::jsonb, '["get in"]'::jsonb, false),
  ('Get off', 'To disembark from a large vehicle or leave a surface', '["I need to get off the train at the next stop."]'::jsonb, '["get off"]'::jsonb, false),
  ('Get on', 'To make progress or continue', '["He needs to get on with his work."]'::jsonb, '["get on"]'::jsonb, false),
  ('Get on with', 'To have a good relationship or get along with someone', '["I get on with my new coworkers really well."]'::jsonb, '["get on with"]'::jsonb, false),
  ('Get on with', 'To continue doing a task or get back to work without delay', '["Stop procrastinating and get on with your work."]'::jsonb, '["get on with"]'::jsonb, false),
  ('Get out', 'To leave an enclosed space or small vehicle', '["Get out of the house, it''s on fire!"]'::jsonb, '["Get out"]'::jsonb, false),
  ('Get over', 'To recover from an illness or emotional distress', '["It took her a long time to get over the loss of her pet."]'::jsonb, '["get over"]'::jsonb, false),
  ('Get through', 'To finish or complete', '["I have a lot of work to get through today."]'::jsonb, '["get through"]'::jsonb, false),
  ('Give off', 'To emit a physical property such as heat, light, or smell', '["The rotting leaves gave off a terrible smell."]'::jsonb, '["gave off"]'::jsonb, false),
  ('Give off', 'To radiate a certain emotional energy or vibe', '["She always gives off a very confident vibe."]'::jsonb, '["gives off"]'::jsonb, false),
  ('Go away', 'To leave or depart', '["Can you please go away and leave me alone?"]'::jsonb, '["go away"]'::jsonb, false),
  ('Go back', 'To return to a previous location or time', '["We go back to visit our hometown every summer."]'::jsonb, '["go back"]'::jsonb, false),
  ('Go by', 'To pass or elapse', '["Time goes by so quickly when you''re having fun."]'::jsonb, '["goes by"]'::jsonb, false),
  ('Go on', 'To continue or proceed', '["Please go on with your presentation."]'::jsonb, '["go on"]'::jsonb, false),
  ('Go out', 'To leave one''s place of residence or to socialize for entertainment', '["Let''s go out for dinner tonight."]'::jsonb, '["go out"]'::jsonb, false),
  ('Go through', 'To experience or endure', '["She had to go through a lot of difficulties to achieve her goals."]'::jsonb, '["go through"]'::jsonb, false),
  ('Go with', 'To match or be suitable for', '["The red shoes go with my dress perfectly."]'::jsonb, '["go with"]'::jsonb, false),
  ('Hand out', 'To distribute or give items to multiple people', '["The teacher will hand out the exam papers."]'::jsonb, '["hand out"]'::jsonb, false),
  ('Hand in', 'To submit work or an item to a teacher, boss, or official', '["Please hand in your homework by Friday."]'::jsonb, '["hand in"]'::jsonb, false),
  ('Hang about', 'To linger or wait around', '["He likes to hang about in the park after school."]'::jsonb, '["hang about"]'::jsonb, false),
  ('Hang around', 'To spend time in a place without any specific purpose', '["We used to hang around the mall when we were teenagers."]'::jsonb, '["hang around"]'::jsonb, false),
  ('Hold on', 'To wait or remain on the line', '["Please hold on while I transfer your call."]'::jsonb, '["hold on"]'::jsonb, false),
  ('Keep in', 'To retain or maintain something within a confined space or boundary', '["He always keeps in his emotions and rarely shows them."]'::jsonb, '["keeps in"]'::jsonb, false),
  ('Keep on', 'To continue doing something persistently, usually followed by a gerund (-ing verb)', '["If you keep on practicing, you will master it."]'::jsonb, '["keep on"]'::jsonb, false),
  ('Keep up with', 'To maintain the same pace or level as someone or something', '["It''s hard to keep up with all the latest technology."]'::jsonb, '["keep up with"]'::jsonb, false),
  ('Keep up', 'To maintain the same speed or standard as others', '["Walk a bit slower, I can''t keep up with you!"]'::jsonb, '["keep up"]'::jsonb, false),
  ('Keep up', 'To continue at the same level of performance or quality', '["Keep up the good work!"]'::jsonb, '["Keep up"]'::jsonb, false),
  ('Knock down', 'To demolish or destroy', '["They plan to knock down the old building and construct a new one."]'::jsonb, '["knock down"]'::jsonb, false),
  ('Lay off', 'To terminate someone''s employment', '["The company had to lay off several employees due to financial problems."]'::jsonb, '["lay off"]'::jsonb, false),
  ('Leave out', 'To omit or exclude', '["She accidentally left out an important detail in her report."]'::jsonb, '["left out"]'::jsonb, false),
  ('Let down', 'To disappoint or fail someone', '["He promised to help but he let us down when he didn''t show up."]'::jsonb, '["let","down"]'::jsonb, false),
  ('Let in', 'To allow someone to enter', '["Please let me in the room; I forgot my key."]'::jsonb, '["let","in"]'::jsonb, false),
  ('Let off', 'To release or excuse from a punishment', '["The police officer decided to let him off with a warning."]'::jsonb, '["let","off"]'::jsonb, false),
  ('Look after', 'To take care of or watch over', '["She needs to look after her younger siblings while their parents are away."]'::jsonb, '["look after"]'::jsonb, false),
  ('Look down on', 'To view with contempt or consider inferior', '["She looks down on people who don''t have a college education."]'::jsonb, '["looks down on"]'::jsonb, false),
  ('Look forward to', 'To anticipate or be excited about', '["I''m really looking forward to our vacation next month."]'::jsonb, '["looking forward to"]'::jsonb, false),
  ('Look into', 'To investigate or examine', '["The authorities will look into the matter and take appropriate action."]'::jsonb, '["look into"]'::jsonb, false),
  ('Look out for', 'To watch or be vigilant for something or someone', '["Look out for any signs of danger."]'::jsonb, '["Look out for"]'::jsonb, false),
  ('Look up to', 'To admire or respect someone', '["I look up to my older sister for her achievements."]'::jsonb, '["look up to"]'::jsonb, false),
  ('Make out', 'To understand or see something unclear or distant', '["I can''t make out the words on the sign from here."]'::jsonb, '["make out"]'::jsonb, false),
  ('Make out', 'To engage in passionate kissing', '["They were caught making out in the park."]'::jsonb, '["making out"]'::jsonb, false),
  ('Make up', 'To invent or create a story or excuse', '["He made up a silly excuse for being late."]'::jsonb, '["made up"]'::jsonb, false),
  ('Make up', 'To reconcile or restore a friendly relationship', '["After their argument they decided to make up and be friends again."]'::jsonb, '["make up"]'::jsonb, false),
  ('Mix up', 'To confuse or mistake something or someone', '["She always mixes up our names."]'::jsonb, '["mixes up"]'::jsonb, false),
  ('Pass away', 'To die', '["Her grandfather passed away last night."]'::jsonb, '["passed away"]'::jsonb, false),
  ('Pass on', 'To transmit or convey something', '["Please pass on the message to the team."]'::jsonb, '["pass on"]'::jsonb, false),
  ('Pass out', 'To faint or lose consciousness temporarily', '["He felt dizzy and passed out during the presentation."]'::jsonb, '["passed out"]'::jsonb, false),
  ('Pass up', 'To miss or decline an opportunity', '["Don''t pass up the chance to travel the world."]'::jsonb, '["pass up"]'::jsonb, false),
  ('Pay off', 'To yield a successful or positive result', '["Working hard for that promotion really paid off."]'::jsonb, '["paid off"]'::jsonb, false),
  ('Pay off', 'To completely eliminate a debt by making the final payment', '["I am finally going to pay off my student loans this year."]'::jsonb, '["pay off"]'::jsonb, false),
  ('Pick out', 'To choose or select something from a range of options', '["I need to pick out a new outfit for the wedding."]'::jsonb, '["pick out"]'::jsonb, false),
  ('Pick out', 'To identify or spot someone or something among others', '["Can you pick out the best photo from the vacation?"]'::jsonb, '["pick out"]'::jsonb, false),
  ('Pick up', 'To physically lift something from the ground or a surface', '["I need to pick up my jacket from the floor."]'::jsonb, '["pick up"]'::jsonb, false),
  ('Pick up', 'To collect or retrieve something or someone', '["Could you pick up the groceries from the store on your way home?"]'::jsonb, '["pick up"]'::jsonb, false),
  ('Pick up', 'To collect someone in a vehicle and take them somewhere', '["I will pick you up from the airport at 5 PM."]'::jsonb, '["pick","up"]'::jsonb, false),
  ('Point out', 'To indicate or draw attention to something or someone', '["He pointed out the mistake in the report."]'::jsonb, '["pointed out"]'::jsonb, false),
  ('Pull off', 'To succeed in achieving something difficult or impressive', '["She pulled off a flawless performance on stage."]'::jsonb, '["pulled off"]'::jsonb, false),
  ('Put forward', 'To propose or suggest something', '["He put forward a new idea for the project."]'::jsonb, '["put forward"]'::jsonb, false),
  ('Put off', 'To postpone or delay something', '["We had to put off the meeting until next week."]'::jsonb, '["put off"]'::jsonb, false),
  ('Put up with', 'To tolerate or endure something', '["She had to put up with his constant complaining."]'::jsonb, '["put up with"]'::jsonb, false),
  ('Put up', 'To assemble or display', '["They put up their artwork for the gallery show."]'::jsonb, '["put up"]'::jsonb, false),
  ('Run away', 'To escape or flee from a place or situation', '["The child decided to run away from home."]'::jsonb, '["run away"]'::jsonb, false),
  ('Run into', 'To meet or encounter someone by chance', '["I ran into an old friend at the grocery store."]'::jsonb, '["ran into"]'::jsonb, false),
  ('Run off', 'To leave quickly or suddenly', '["He ran off without saying goodbye."]'::jsonb, '["ran off"]'::jsonb, false),
  ('Run out of', 'To use up or exhaust the supply of something', '["We ran out of milk so I need to go to the store."]'::jsonb, '["ran out of"]'::jsonb, false),
  ('Set off', 'To start a journey or trip', '["We set off early in the morning to avoid traffic."]'::jsonb, '["set off"]'::jsonb, false),
  ('Set off', 'To trigger or initiate something such as a series of events', '["Her comments set off a heated debate among the panelists."]'::jsonb, '["set off"]'::jsonb, false),
  ('Set up', 'To establish or arrange something', '["They set up a new business together."]'::jsonb, '["set up"]'::jsonb, false),
  ('Settle down', 'To calm down or become established in a stable life', '["After traveling for years she decided to settle down in a small town."]'::jsonb, '["settle down"]'::jsonb, false),
  ('Settle in', 'To become accustomed or get comfortable in a new place', '["It took some time for them to settle in their new home."]'::jsonb, '["settle in"]'::jsonb, false),
  ('Settle up', 'To pay a debt or resolve financial matters', '["They need to settle up the bill before leaving the restaurant."]'::jsonb, '["settle up"]'::jsonb, false),
  ('Show off', 'To display or demonstrate one''s skills or possessions', '["He loves to show off his new car to everyone."]'::jsonb, '["show off"]'::jsonb, false),
  ('Show up', 'To arrive or appear especially unexpectedly or at a specified time', '["She showed up at the party wearing a stunning dress."]'::jsonb, '["showed up"]'::jsonb, false),
  ('Shut down', 'To close or stop the operation of a business or system', '["The company decided to shut down its manufacturing plant."]'::jsonb, '["shut down"]'::jsonb, false),
  ('Shut down', 'To dismiss or reject an idea proposal or argument', '["The team leader immediately shut down his suggestion."]'::jsonb, '["shut down"]'::jsonb, false),
  ('Sit down', 'To take a seat or position oneself comfortably', '["Let''s sit down and discuss the details of the project."]'::jsonb, '["sit down"]'::jsonb, false),
  ('Stand out', 'To be noticeably different or exceptional', '["Her talent stands out among the other contestants."]'::jsonb, '["stands out"]'::jsonb, false),
  ('Stand up to', 'To confront or resist someone or something', '["He decided to stand up to the bully."]'::jsonb, '["stand up to"]'::jsonb, false),
  ('Stick around', 'To remain or stay in a place or situation', '["Can you stick around until I finish this task?"]'::jsonb, '["stick around"]'::jsonb, false),
  ('Take after', 'To resemble or have similar traits as someone', '["She takes after her mother in terms of looks and personality."]'::jsonb, '["takes after"]'::jsonb, false),
  ('Take apart', 'To disassemble or dismantle something', '["We need to take apart the furniture before moving it."]'::jsonb, '["take apart"]'::jsonb, false),
  ('Take back', 'To retract or withdraw a statement or offer', '["I want to take back what I said earlier."]'::jsonb, '["take back"]'::jsonb, false),
  ('Take back', 'To return something to its original location or owner', '["Could you please take back this book to the library?"]'::jsonb, '["take back"]'::jsonb, false),
  ('Take down', 'To write or record something', '["Please take down the important points of the meeting."]'::jsonb, '["take down"]'::jsonb, false),
  ('Take in', 'To understand or comprehend something', '["I couldn''t take in all the information at once."]'::jsonb, '["take in"]'::jsonb, false),
  ('Take on', 'To undertake or accept a responsibility or challenge', '["He decided to take on the project despite the difficulties."]'::jsonb, '["take on"]'::jsonb, false),
  ('Take over', 'To assume control or become dominant', '["The new manager will take over the department next week."]'::jsonb, '["take over"]'::jsonb, false),
  ('Take up', 'To start or begin a hobby activity or occupation', '["I want to take up playing the piano."]'::jsonb, '["take up"]'::jsonb, false),
  ('Talk over', 'To discuss or consider something with others', '["Let''s talk over the details of the project."]'::jsonb, '["talk over"]'::jsonb, false),
  ('Think over', 'To consider or reflect on something', '["I need some time to think over your proposal."]'::jsonb, '["think over"]'::jsonb, false),
  ('Throw away', 'To discard or get rid of something', '["She decided to throw away the old magazines."]'::jsonb, '["throw away"]'::jsonb, false),
  ('Try for', 'To attempt to achieve or obtain something', '["He will try for a promotion at work."]'::jsonb, '["try for"]'::jsonb, false),
  ('Try on', 'To test or experiment with wearing something', '["She wants to try on the dress before buying it."]'::jsonb, '["try on"]'::jsonb, false),
  ('Try out', 'To test or evaluate something', '["They decided to try out the new software."]'::jsonb, '["try out"]'::jsonb, false),
  ('Turn down', 'To reject or refuse an offer or request', '["She turned down the job offer because of the low salary."]'::jsonb, '["turned down"]'::jsonb, false),
  ('Use up', 'To deplete or exhaust the supply or quantity of something', '["We used up all the printer ink."]'::jsonb, '["used up"]'::jsonb, false),
  ('Wake up', 'To stop sleeping and become conscious', '["I usually wake up early in the morning."]'::jsonb, '["wake up"]'::jsonb, false),
  ('Walk away', 'To leave or abandon a situation or relationship', '["He decided to walk away from the argument."]'::jsonb, '["walk away"]'::jsonb, false),
  ('Walk out', 'To leave suddenly or in protest', '["The audience walked out during the boring performance."]'::jsonb, '["walked out"]'::jsonb, false),
  ('Watch out', 'To be cautious or vigilant', '["Watch out for the step it''s slippery."]'::jsonb, '["Watch out"]'::jsonb, false),
  ('Wear off', 'To gradually fade or disappear', '["The effects of the medication will wear off in a few hours."]'::jsonb, '["wear off"]'::jsonb, false),
  ('Work off', 'To eliminate or reduce through physical activity or effort', '["I need to work off the extra calories I consumed."]'::jsonb, '["work off"]'::jsonb, false),
  ('Work up', 'To develop or generate a particular feeling or state', '["I''m trying to work up the courage to ask her out."]'::jsonb, '["work up"]'::jsonb, false),
  ('Write down', 'To record or write something on paper', '["Please write down the important details."]'::jsonb, '["write down"]'::jsonb, false),
  ('Write off', 'To consider something as a loss or failure', '["They had to write off the damaged goods."]'::jsonb, '["write off"]'::jsonb, false),
  ('Write up', 'To write a report summary or account of something', '["I need to write up the meeting minutes."]'::jsonb, '["write up"]'::jsonb, false),
  ('Zip up', 'To fasten or close a zipper', '["She forgot to zip up her jacket before going outside."]'::jsonb, '["zip up"]'::jsonb, false),
  ('Pay back', 'To return money that you borrowed from someone', '["Could you lend me $20 for lunch? I''ll pay you back on Friday."]'::jsonb, '["pay","back"]'::jsonb, false),
  ('Pay out', 'To distribute or disburse money from a fund or account', '["The insurance company will pay out the claim next week."]'::jsonb, '["pay out"]'::jsonb, false),
  ('Give out', 'To distribute or hand items to multiple people', '["The teacher gave out the exam papers to all the students."]'::jsonb, '["gave out"]'::jsonb, false),
  ('Look up', 'To check the meaning of something', '["If you don''t know the meaning of a word you should look it up in the dictionary."]'::jsonb, '["look","up"]'::jsonb, false),
  ('Give up', 'To stop trying; surrender', '["After two weeks of trying to build my own table I gave up and just bought one."]'::jsonb, '["gave up"]'::jsonb, false),
  ('Give away', 'To donate or permanently hand something over without charge', '["They decided to give away their old clothes to charity."]'::jsonb, '["give away"]'::jsonb, false),
  ('Give away', 'To accidentally reveal a secret or betray someone', '["Her nervous smile gave her away."]'::jsonb, '["gave","away"]'::jsonb, false),
  ('Hold back', 'To stop yourself from doing or saying something', '["Amy has a great voice but whenever she''s singing in public she feels shy and holds back."]'::jsonb, '["holds back"]'::jsonb, false),
  ('Drop off', 'To transport someone or something somewhere and leave them there', '["Can you drop me off at the grocery store on your way home?"]'::jsonb, '["drop","off"]'::jsonb, false),
  ('Work out', 'To come up with a solution or a compromise', '["Don''t worry I''m sure we can work something out so that everyone is happy."]'::jsonb, '["work","out"]'::jsonb, false),
  ('Drop by', 'To make a brief, casual stop at a place while passing through an area', '["Feel free to drop by the office if you''re in the neighborhood."]'::jsonb, '["drop by"]'::jsonb, false),
  ('Drop in', 'To visit someone without making an appointment', '["Drop in to my office anytime."]'::jsonb, '["Drop in"]'::jsonb, false),
  ('Check out', 'To examine or try something to learn more about it', '["Check out my new car!"]'::jsonb, '["Check out"]'::jsonb, false),
  ('Take out', 'To remove or extract something from a container, place, or person', '["Please take out the trash."]'::jsonb, '["take out"]'::jsonb, false),
  ('Take out', 'To escort someone on a date', '["He took her out to the most expensive restaurant in the city."]'::jsonb, '["took","out"]'::jsonb, false),
  ('Take away', 'To remove something from someone so they no longer have access to it', '["The teacher had to take away the students'' phones."]'::jsonb, '["take away"]'::jsonb, false),
  ('Take away', 'To eliminate or significantly reduce a pain, problem, or feeling', '["The painkillers will take away the headache."]'::jsonb, '["take away"]'::jsonb, false),
  ('Turn on', 'To switch a machine or light on', '["Turn on the light I''m not trying to sleep!"]'::jsonb, '["Turn on"]'::jsonb, false),
  ('Turn off', 'To switch a machine or light off', '["Turn off the light I''m trying to sleep!"]'::jsonb, '["Turn off"]'::jsonb, false),
  ('Cheer on', 'To support someone through words of encouragement', '["Even though Samantha was in last place her brother cheered her on through the entire race."]'::jsonb, '["cheered","on"]'::jsonb, false),
  ('Fill in', 'To do someone else''s job temporarily', '["Can you fill in for me while I''m on vacation?"]'::jsonb, '["fill in"]'::jsonb, false),
  ('Put out', 'To extinguish a fire', '["The firefighters managed to put out the fire before it spread to other houses."]'::jsonb, '["put out"]'::jsonb, false),
  ('Put out', 'To irritate someone by asking them for a favor', '["I''d ask you to make me dinner but I don''t want to put you out."]'::jsonb, '["put","out"]'::jsonb, false),
  ('Put on', 'To get your clothes or makeup on', '["Every morning she puts on her dress lipstick shoes and hat—in that order."]'::jsonb, '["puts on"]'::jsonb, false),
  ('Take off', 'To remove clothing or something worn on the body', '["Please take off your shoes before coming inside."]'::jsonb, '["take off"]'::jsonb, false),
  ('Fill out', 'To complete a form by providing required information', '["Please fill out the application form and submit it by Friday."]'::jsonb, '["fill out"]'::jsonb, false),
  ('Cheer up', 'To show support to someone who seems sad or to try to make someone happier', '["Andrew was having a bad day so his girlfriend cheered him up by taking him out for ice cream."]'::jsonb, '["cheered","up"]'::jsonb, false),
  ('Cut off', 'To interrupt or stop something', '["His father is rich but he cut him off without any money of his own."]'::jsonb, '["cut","off"]'::jsonb, false),
  ('Cut out', 'To stop it', '["Hey cut it out! I was watching that movie so stop changing the channel!"]'::jsonb, '["cut","out"]'::jsonb, false),
  ('Call off', 'To cancel something', '["We had to call off the picnic because of the rain."]'::jsonb, '["call off"]'::jsonb, false),
  ('Bring up', 'To mention something', '["Mark was sick and had to miss the party so please don''t bring it up I don''t want him to feel bad for missing it."]'::jsonb, '["bring","up"]'::jsonb, false),
  ('Bring on', 'To cause something to happen usually something negative', '["His lung cancer was brought on by years of smoking."]'::jsonb, '["brought on"]'::jsonb, false),
  ('Bring on', 'To accept a challenge with confidence', '["You want to have a race? Bring it on! I can beat you!"]'::jsonb, '["Bring","on"]'::jsonb, false),
  ('Call on', 'To visit someone', '["I''ll call on you this evening to see how you''re feeling."]'::jsonb, '["call on"]'::jsonb, false),
  ('Warm up to', 'To start liking someone or something more as you spend more time with them', '["The new puppy was scared of my husband when we first got him but he warmed up to him pretty quickly."]'::jsonb, '["warmed up to"]'::jsonb, false),
  ('Come across', 'To meet or find by chance', '["I was cleaning the attic and I came across my high school uniform. Can you believe it still fits?"]'::jsonb, '["came across"]'::jsonb, false),
  ('Get back at', 'To get revenge on someone', '["Her ex-husband took her house so she got back at him by taking his dogs."]'::jsonb, '["got back at"]'::jsonb, false),
  ('Go out with', 'To go on a date with someone', '["Sarah was so happy when Peter finally asked her to go out with him!"]'::jsonb, '["go out with"]'::jsonb, false),
  ('Log in', 'To sign in to your account on a website or computer', '["Don''t forget to log in to your account to learn English better and faster."]'::jsonb, '["log in"]'::jsonb, false),
  ('Pay for', 'To give someone money for a particular purpose', '["She used her credit card to pay for the hotel reservation."]'::jsonb, '["pay for"]'::jsonb, false),
  ('Pay for', 'To suffer because of something you did', '["He''ll pay for all the problems he caused me by being late today!"]'::jsonb, '["pay for"]'::jsonb, false),
  ('Fall for', 'To fall in love with someone', '["He fell for her the moment he saw her."]'::jsonb, '["fell for"]'::jsonb, false),
  ('Cut in', 'To interrupt a conversation or activity', '["The teacher cut him in and asked him to explain the answer to the class."]'::jsonb, '["cut","in"]'::jsonb, false),
  ('Call on', 'To use someone''s or something''s knowledge', '["I may need to call on the university''s excellent professors in order to answer your question."]'::jsonb, '["call on"]'::jsonb, false),
  ('Drop out', 'To quit or stop participating in something', '["She was a straight-A student but she dropped out of college to pursue her dream of becoming an artist."]'::jsonb, '["dropped out"]'::jsonb, false),
  ('Log out', 'To sign out of your account', '["You should always log out of your accounts when you use a public computer."]'::jsonb, '["log out"]'::jsonb, false),
  ('Log off', 'To sign out of your account', '["You should always log off of your accounts when you use a public computer."]'::jsonb, '["log off"]'::jsonb, false),
  ('Look out', 'To be vigilant for something', '["Look out there''s a baseball coming your way!"]'::jsonb, '["Look out"]'::jsonb, false),
  ('Come up', 'To be mentioned or brought up in conversation', '["The new project came up during our team meeting."]'::jsonb, '["came up"]'::jsonb, false),
  ('Come up', 'When something happens unexpectedly', '["I was going to meet my friends for dinner but something came up so I had to cancel."]'::jsonb, '["came up"]'::jsonb, false),
  ('Come forward', 'To volunteer information about something like a crime', '["The police are encouraging people to come forward with any information about the kidnapped girl."]'::jsonb, '["come forward"]'::jsonb, false),
  ('Check in', 'To register at a hotel for a stay', '["We haven''t checked in at the hotel yet."]'::jsonb, '["checked in"]'::jsonb, false),
  ('End up', 'To eventually be in a particular place or situation', '["After driving around for hours we finally ended up at the beach."]'::jsonb, '["ended up"]'::jsonb, false),
  ('Fall apart', 'To stop working or break into pieces', '["The old chair fell apart when I sat on it."]'::jsonb, '["fell apart"]'::jsonb, false),
  ('Fall down', 'To collapse or fall to the ground', '["The little girl tripped and fell down the stairs."]'::jsonb, '["fell down"]'::jsonb, false),
  ('Fall off', 'To decline in quality or quantity', '["Sales fell off during the holiday season."]'::jsonb, '["fell off"]'::jsonb, false),
  ('Give out', 'To break down or stop functioning due to exhaustion or overuse', '["His car engine finally gave out in the middle of nowhere."]'::jsonb, '["gave out"]'::jsonb, false),
  ('Go ahead', 'To go in front of someone or to give permission', '["You can go ahead and start the meeting without me."]'::jsonb, '["go ahead"]'::jsonb, false),
  ('Grow up', 'To tell someone to stop acting childish', '["Some people tell Steve he needs to grow up but he loves acting like a child."]'::jsonb, '["grow up"]'::jsonb, false),
  ('Grow apart', 'To get distant from someone like a friend', '["When my friend moved to a different country I tried to stay close with her but we slowly grew apart."]'::jsonb, '["grew apart"]'::jsonb, false),
  ('Hang on', 'To keep something', '["When everyone else was getting fired Paul managed to hang on to his job."]'::jsonb, '["hang on"]'::jsonb, false),
  ('Hang out', 'To spend time with someone casually', '["My friends and I used to hang out in the park after school."]'::jsonb, '["hang out"]'::jsonb, false),
  ('Hang up', 'To end a phone call especially if before the other person is ready', '["I was in the middle of a sentence and he hung up on me! How rude."]'::jsonb, '["hung up"]'::jsonb, false),
  ('Hold on', 'To grasp something tightly', '["You''d better hold on to your hat; it''s windy out there!"]'::jsonb, '["hold on"]'::jsonb, false),
  ('Hold on', 'To ask someone to wait for a moment', '["Hold on I''ll be right back."]'::jsonb, '["Hold on"]'::jsonb, false),
  ('Give in', 'To surrender especially in a fight or argument', '["Ben''s mother gave in and let him stay out late with his friends."]'::jsonb, '["gave in"]'::jsonb, false),
  ('Take off', 'For an aircraft to leave the ground and become airborne', '["The airplane is scheduled to take off at 8:00 PM."]'::jsonb, '["take off"]'::jsonb, false),
  ('Take off', 'To leave a place suddenly or in a hurry', '["She saw her ex and decided to take off."]'::jsonb, '["take off"]'::jsonb, false),
  ('Take off', 'To suddenly become very successful or popular', '["His startup really took off after that investor called."]'::jsonb, '["took off"]'::jsonb, false),
  ('Turn around', 'To move so you''re facing the opposite direction', '["Sally was about to get on the plane but she turned around when someone called her name."]'::jsonb, '["turned around"]'::jsonb, false),
  ('Turn up', 'When something that was lost is found unexpectedly', '["Anything I lose usually turns up under the couch. It''s my cat''s favorite hiding place."]'::jsonb, '["turns up"]'::jsonb, false),
  ('Work out', 'To exercise', '["I try to work out every morning by repeatedly lifting a heavy donut to my mouth."]'::jsonb, '["work out"]'::jsonb, false);
