---
- name: Undeploy backend
  ansible.builtin.import_tasks: backend.yml
  tags: [backend]

- name: Undeploy frontend
  ansible.builtin.import_tasks: frontend.yml
  tags: [frontend]

- name: Undeploy redirect for old domains
  ansible.builtin.import_tasks: redirect.yml
  tags: [redirect]

- name: Undeploy PostgreSQL
  ansible.builtin.import_tasks: postgres.yml
  tags: [postgres]
