all:
  hosts:
    hetzner1:
      # todo: remove it form project or make as env. variable
      ansible_host: 116.203.78.118
      ansible_user: vpsuser
      ansible_ssh_private_key_file: "~/dev/scripts/vps/ssh-key-h1.key"
