---
# Tear down components
#   ansible-playbook playbooks/undeploy.yml --tags backend
#   ansible-playbook playbooks/undeploy.yml --tags frontend
#   ansible-playbook playbooks/undeploy.yml --tags postgres
#   ansible-playbook playbooks/undeploy.yml                   (everything)

- name: Undeploy application
  hosts: hetzner1
  become: true
  roles:
    - role: undeploy
