spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/phrasaldb
    username: phrasaluser
    password: phrasalpass
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    show-sql: false

  flyway:
    enabled: true

server:
  port: 28080

logging:
  level:
    net.phrasal: INFO
    org.hibernate.SQL: WARN
