---
- name: Swap setup
  ansible.builtin.include_tasks: swap.yml
  tags: [swap]

- name: PostgreSQL setup
  ansible.builtin.import_tasks: postgres.yml
  tags: [postgres]

- name: Java setup
  ansible.builtin.import_tasks: java.yml
  tags: [java]

- name: Nginx setup
  ansible.builtin.import_tasks: nginx.yml
  tags: [nginx]

- name: Firewall setup
  ansible.builtin.import_tasks: firewall.yml
  tags: [firewall]
