apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: backend
data:
  database.url: jdbc:postgresql://postgres-service:5432/phrasaldb
  spring.profiles.active: dev
  server.port: "8080"
