apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  labels:
    app: phrasal-frontend
data:
  default.conf: |
    map $http_user_agent $loggable {
        ~kube-probe 0;
        default     1;
    }

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        access_log /var/log/nginx/access.log combined if=$loggable;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location = /api {
            proxy_pass         http://backend:8080/api;
            proxy_read_timeout    30s;
            proxy_connect_timeout 30s;
            proxy_send_timeout    30s;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   X-Forwarded-Host  $host;
            proxy_set_header   X-Forwarded-Port  3000;
        }

        location /api/ {
            proxy_pass         http://backend:8080/api/;
            proxy_read_timeout    30s;
            proxy_connect_timeout 30s;
            proxy_send_timeout    30s;
            proxy_set_header   Host              $http_host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   X-Forwarded-Host  $host;
            proxy_set_header   X-Forwarded-Port  3000;
        }
    }
